{% set version = "4.6.1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-bigmemory
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/bigmemory_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/bigmemory/bigmemory_{{ version }}.tar.gz
  sha256: b56e157c87ed6c4fc69d4cb9c697ae9a2001726e776e41aa7c48b35327b65141

build:
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}sed               # [win]
    - {{ posix }}grep              # [win]
    - {{ posix }}autoconf
    - {{ posix }}automake          # [not win]
    - {{ posix }}automake-wrapper  # [win]
    - {{ posix }}pkg-config
    - {{ posix }}make
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-bh
    - r-rcpp
    - r-bigmemory.sri
    - r-uuid >=1.0_2
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    #- r-bh
    - r-rcpp
    - r-bigmemory.sri
    - r-uuid >=1.0_2

test:
  commands:
    - $R -e "library('bigmemory')"           # [not win]
    - "\"%R%\" -e \"library('bigmemory')\""  # [win]

about:
  home: https://github.com/kaneplusplus/bigmemory
  license: LGPL-3.0-only OR Apache-2.0
  summary: Create, store, access, and manipulate massive matrices. Matrices are allocated to shared memory and may use memory-mapped files.  Packages 'biganalytics', 'bigtabulate', 'synchronicity', and 'bigalgebra' provide advanced functionality.
  license_family: LGPL
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/LGPL-3

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: bigmemory
# Version: 4.5.36
# Title: Manage Massive Matrices with Shared Memory and Memory-Mapped Files
# Author: Michael J. Kane <kaneplusplus@gmail.com>, John W. Emerson <jayemerson@gmail.com>, Peter Haverty <haverty.peter@gene.com>, and Charles Determan Jr. <cdetermanjr@gmail.com>
# Maintainer: Michael J. Kane <bigmemoryauthors@gmail.com>
# Contact: Mike, Jay, and Charles <bigmemoryauthors@gmail.com>
# Depends: R (>= 3.2.0),
# Imports: methods, Rcpp, utils, bigmemory.sri
# Enhances: biganalytics, bigtabulate
# LinkingTo: BH, Rcpp
# Description: Create, store, access, and manipulate massive matrices. Matrices are allocated to shared memory and may use memory-mapped files.  Packages 'biganalytics', 'bigtabulate', 'synchronicity', and 'bigalgebra' provide advanced functionality.
# License: LGPL-3 | Apache License 2.0
# URL: https://github.com/kaneplusplus/bigmemory
# BugReports: https://github.com/kaneplusplus/bigmemory/issues
# LazyLoad: yes
# Biarch: yes
# Suggests: testthat
# RoxygenNote: 7.0.2
# NeedsCompilation: yes
# Packaged: 2019-12-23 00:36:34 UTC; mike
# Repository: CRAN
# Date/Publication: 2019-12-23 17:59:40 UTC
