travis:
  secure:
    BINSTAR_TOKEN: GnsN+m7bQlga35NaY0UYDzdY31e86zI9vwqrd7CV9jwQQ7uPdqfYU+IBBPkChN1C3/OILnr7vKYaMRMEqXO99cQ7Iv+yUxQb/LA4Phbmlepg1DaVupSBHlY39/qxHCxZTy0XBSffRQRHHxePTPoJueGWh0fF0wex2YXR8q7cA80jq6tJD+2R9ozPBc1oFCk3Wcyh11+7Guhvije+PBfZj2RfCPZ+1OUC7lgVZGpdXzrtF/SS3urh/1cHdkJ+2Otc3JiQRBztzU+w1V5TrpD7CVC71e+yuARVyufpdKi55eNaJ+IyZhuJI5UNOvuA4tG6xoYi1JfEKc6FbqZF8Y5dLcQgJdq/6u9U4VBmnFN2q4lSwT/Ez5UtaKR04bUNIFlmjjP2w7sNpyRinEQcg8uyzi3TnFgHkFR2c2w3krssxSda/q/50gCamH6OLYD2L39aJraAxrDJmJaj1RcILNuHwMQOR71kAgQh3Yg2BYL5srwcymHK+lvOdVftvvRkoyKoam891t6izrVcE+OxUWwlQU2UoRVNgrupM26jogGeXSMS1Tm1TkXoX7PXpy/nBbqOHWpzE9smKO5GqYX2gn2yuOk/mjnfld5r8FsEI2HJa0iLe3K5YWBreEhrVffFXSQX9lwUAEiau4ttdChmrfwvmKaPVgYOKILo2IDIuFNhnMU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
