travis:
  secure:
    BINSTAR_TOKEN: fYzBQoyI9asUjuqXePbZyBh0PH3kIn6zMc0PvBjp+JFiU9QtxLzTc9OurhOnI+s09mg3/tkI6gxKhxGph0o0pv9vIUuh4PPLaZgQ08+4u76+9B7P+P+WGGaUDZKeQPlBxmSiqHqwUeWZUaE8icEEVg7k21yKkfESbQXWFj04yNUwqcLIeOPdULsQcughvNpOtqESFsSDAfCVVLLvNkoHRYFybFWh9VgGX80eCFBNv5/XtuwG5nshJ1gyPiATSQy6/WHD0FH0wNbXSQ3AntGvV33AXuobwqmmPlCLMWkEvyeKvHklf9AnXf3otJK9QitaE8oPjQjvnCGrzV3jAH9wEu6xAZg2XRQ8IoMpbSuIFw+gqc9WHPQz3uwmIn11/FM8m+CjEwHLDhLca9GMNtyfYDOGauhp/yeAELxVC5XxkwxAw3SMMJLMiRw3EnTmgClvgURvzBKWrwl2el6HKjxB5W1dOUBLbARMx+FYZds6tcHGAQqNet9tXY2P2mWqJmCbg5kqfOY0BYzmnw7XmQOe2if0TU8cMu0OQ1Csx7K371AbMWVXXGnpQj/AIsZCntZMLYjSescSiEUBji/c623v5u73FbEUmps43BJMUwmJKhZ7CddXkDGvUvyUDB7u6vXkLEZGx9mysEk0n1IeakREZbiCKgjZ21/VFoDbwo6uPC4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
