appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: TUUouJwi5wgb9zi/NldNClJQ04o4IwoqPGl5vAOy5KyW2JuM+N3T6YPxn+X8pMWgDuHq4ITWoX2srFaPsB8/DATB7OzsUtKQJBlIITRXoL6IaBCHpVFJ06EyqbPLTdloNccKsh0ThTIKE30shZ4k6J+k3PX0SoRO5YsYCuODhf1q6yTtwZSBFPfY3SnH3MFquo1vtYwRBpmk6K4P/fJRDQaKMVfqjSStWTzyTYu4fDD7MFFEMJ5WbfES2bQV88lO0NtF+wsdO7LdWGU6TZ/IuoBBGBdCJJtKAbfUFhAhYTFH15lHR1cAazQL7tsTkgicUZj51gZb1V/YT9u8cjPVLdS/GVpL2kJXIEFcTF5QCfhQ40grAxQqUH4KmelToh54EB9rLcZsGiSuM5YwAPG8AL06dFDjS+I5lKObc+iR+HFIIzABT//0HSTyTY4S2hKJljSwUdMd4vezBq/tNLM/RuMIOZPyMLUIS68/1+csSAM2uMgxxKCqpGsgO7aRuA2J7yLbWDSFBJVSTfLC9l/0vYnbxAXOImhAbfMThFg7Sz+YRkZI4+H8FwDCkMNBsXzlVfgYtFC42cpuTSGWqVRtj3hKsfJHzS1wXr8X2G4u3n1JDqmDVd+Q6I/Xs3+Vi60rZY/cr0V56qd8c3iPFAjIzK1+UtZORLX8lg5z1/YslSM=}
