travis:
  secure:
    BINSTAR_TOKEN: LtSJRPnhXMRb8LfvQCT5NvYW92Cw4hLGWwZWrw6qJqdRVvOCQnQ28EzzdOGHMa2IHZW88iVpJv5Sqn0Vjr/PtIHbnYOHA1JOIZod5xe5NpbeWnjeufVL89HohNA4c29fwbGRU4JR62O2PvPL/hrrOuqHF/ZnBhx8+L90h0M9zx7vaxTAndIc2EY5aV18w/6PRXAOYbEYfDszRHqz6vlz8VMKymrK/2DpsDyNVAOB3TMsW6XOxr4BASAsZOWwJ2kyUzmc4bGFxPRoLQ9tKKrhEh4jtXmPaoqf94LY9chNyXB2eESiirAnBLM+Oh4uNn5khgR6onCzhlmEqR/kibRwdDYMnY1a+1PtQNR+6EUmuDkzkrFm+KR799R7H20AzijZ7HGaV2uEDll+jgr4FoZIV3vSogMO9N/khWYK39fXhw/Ee87sf3Xmvdky73IaQByn1xNxua0Oex6uloFI0R1231gdX6/dDiHq2hqXQEHhhgsmOub462NdzYyHI4T9oW2NQo5rtjYW5z1oSBlVMN1EQIeYS7fHJTcxRoKOC5VqZ/p6ISoI5dhlLc4InbFqcIAb1qGwEZILZ1u56JA8Z67OKQpGxQbmAqmQjuPDXIbcmpqbaM/ceT+erWLG0ydPgmpjMAqo5y5f+SiegAgovhZj2LF7mp/M62sm6ndTACKYvl8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
