travis:
  secure:
    BINSTAR_TOKEN: bOlHGkIel77IrQ2VU3e+Or4C390HyGys3FHNfGOf3z0z6Jx7Ogc6oIxf6KQ+vFiQoNVOczonOztJ/j4zCopyPxMFhcUIAoqtrR32RI+9afZvM3fN9w/LpskPx6SSk2BiPkLcH82NC8rj8eqkMCUssuAFc68YqMOwAtkqfMNd1AIi6eeFKkdyOfVQniiPxIY88CYy/sQ0TKCLr1H+5/hruRq9VxBAlRvN9jzDYJl0eegoqBy6H+u0/8E7n70XRUiJzu3Yl94XV+CuBB6sjh48Zu0jlGuaxkgI8kmwygf/FeHtJ/UpDZu6MG2vD5XqA6zULb8Jw6Q/byghixLqFyjdcHU6RvGzOlAsBDRkBnFmI50/ZKvilvG24fXrs5EBWyJ0PS4D7MSgva3Zu/6R0aK/rD1odaQvbVHTzHeUBIuSBilMyCJ+atIfgF8ubPKds5f/LP6ebFxdzvf7iIfiLLcPx7C9DA7yyFiWuwLJZkv8Zd9nCJNFTiPr7Lrw7sdf4o8hF8z1l2BezaDCvdHY/KhEb46BM5rpB0fADgBqsT+DfyC8q6XelIfLLKdLbfA72f4X4V6lOjPs5HrSh49dsJwxUtB1zdzStrgp/g+79pTqrpW3LZ77ayX2A6M6bh+BC81EkIlG/XgFnoWGsJq20l+jaQ1iKaamWz1VP21oUu4xgoo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
