travis:
  secure:
    BINSTAR_TOKEN: jy51sao0FYRWDeBnq6wTYUbKBUyevXxei81EaAXmz5LzobPxrE+6DDHIU9W81FoOFxauCO0bLUTr4z+6yZ/7b/QKkq8TcJs1hx6rOqWw5ePSfgEtaRyOfRJhLl83tJ7UKKe8Z24J1jZ37xuaW2o9Q5rHkdbuZUyxpAutkp9/guBzWey8aeL4ioTLIylVKI6ZEg+mUtDNioQKEyQuUTVhrv1xesNEReh+nLMnvoJERumEt8o8IJ55dhMGjopqlZfvjTSc8HP/bhdwTMNbePowBQw5I1wQTbAeC3X42z6kbY1YfxCjQyJB1zvrwrxGJXIdvr2P8fp9NwGLG23VIfIKgJno6p7vaXZrcBuwrKWsr53DvJked9AEC7VTjLa024ScehX53ttmVc8TYkiIi0yybOnfrb/24BXRK3bH56MuVo7tWBuyVlu/6MFTDJ09tjclHyhcmMpVBjSB4hXV1C/O0HSW5gJ2UiteBl6heOTQ5aRDcdoOcmT8hkuqe1NvvUzwGVTwTUFl49uAUhquSUOC/0iHryqP4JPz0m/9fJgDrOo/wyQ6H83bnMuSs+kAjD0Re5035T4heibMRPxs9YnFpyltat5da4TgeeiCRV4Tx1McCZ+HmMWmS3Rl/sNxBZPDm4XSYlTxykpLGC7mUQDeq4UEAjddjqSQkRKcCBBrdnY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
